version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "acs-auth-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gn4pf6123nnd"
s3_prefix = "acs-auth-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
